### ISSUE TITLE
Wrap a front-end library to control permissions for web UI elements like buttons

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin.js#2]
Node-Casbin is only for backend Node.js applications. It can run on frontend but some functionalities like file read/write, DB access will certainly be disabled. So we need a new library for front-end only. It should be:

1. Can communicate with backend servers (e.g, via Node-Casbin), sync policies into browser.
2. Enforce the policy locally inside a browser.
3. Add some friendly functions especially for web, like `isButtonAllowedToBeClicked()`.

**Comment by Ishaan28malik** [comment]
@hsluoyz I think we can go ahead with React JS here for the front-end                                                                                      
       ```if (user.role === ADMIN || user.auth && post.author === user.id) {
  <button onClick={this.deletePost.bind(this)}>Delete</button>
}```

this is an example piece for a clickable **Delete Button**.

Also there is an option to use [CASL](https://github.com/stalniy/casl) for the same.

**Comment by hsluoyz** [comment]
@Ishaan28malik yes, that example is exactly what I mean. Also a frontend library like CASL is what we want.

1. CASL has supported frameworks like React, Vue via binding. We also want to do similar.
2. But CASL's backend is very weak. They only support MongoDB. But we have Casbin as a very strong backend and we support all kinds of DBs.
3. I think our first step is to make a Casbin-compatible version CASL. Then we will add more our own features.

**Comment by Ishaan28malik** [comment]
@hsluoyz this sounds good, So how are we planning to start with it?
I can help you out with the front-end part.

**Comment by ShaswatJBabhulgaonkar** [comment]
Here we can use role-based access control RBAC which is an approach of restricting system access to authorized users. Considering that we have a login mechanism, we can get the details about all the button ids to associate them with user and call API on the first login and display only if API returns True.

**Comment by hsluoyz** [comment]
See: https://github.com/stalniy/casl

**Comment by Ishaan28malik** [comment]
@hsluoyz I already mentioned this above and let me know how do you want to proceed in this further? I am ready to work upon this.

**Comment by hsluoyz** [comment]
First we will do similar things as: https://github.com/stalniy/casl but we will use cookie to communicate between client and server. I think we are about to get started on casbin.js @kingiw

**Comment by hsluoyz** [comment]
@kingiw let's try the idea to use cookie to get permissions for a user. You can create PR in this repo.

**Comment by kingiw** [comment]
@hsluoyz Got it. I am now investigating the implementation of some other similar projects and designing the overall architecture of our Casbin.js. Maybe I'll have a discussion with you and other mentors later this week.

**Comment by hsluoyz** [comment]
@kingiw it looks like that we already have some code base now. I Hope to see a minimized usable version soon, it means:

1. It has a public API and the public API is documented in casbin.org
2. I will act like a normal user of Casbin, build my own website and try to use your casbin.js product based on the API docs. Actually the website will probably be our forum: https://github.com/casbin/casbin-forum

So you can think about what API should be exposed to user side now. It can be incomplete for this stage. We can start from the most basic ones.

**Comment by kingiw** [comment]
@hsluoyz So you means we are going to design the same Enforcer API as the other Casbin frameworks do?

IMO, Casbin.js is used to manipulate which objects **one** user can access at a front page, that's because:
1. At the frontend, a website serves for one specific user.
2. It's not proper to have all the policies (including those not related to the frontend user) at the frontend due to potential security issues.
From these perspectives, most of the interfaces in the API docs are unnecessary. Casbin.js should provide some APIs for manipulating "policies of a single user "(aka profiles). I will provide a API list for you to review later.

**Comment by hsluoyz** [comment]
> So you means we are going to design the same Enforcer API as the other Casbin frameworks do?

No. Actually I want another CASL, which is well integrated into Casbin backend ecosystem. It should not be the Management API for Casbin backend. Maybe some of RBAC API are OK to reuse. So you can get some idea from CASL API and think about how to integrate it with Casbin backend.

**Comment by kingiw** [comment]
CASL is similar with Node-Casbin instead of Casbin.js. The core of CASL is to set the access rules and check the permissions. To be specific, Casbin.js should provide some functionalities that the CASL support at some popular frontend library. All the management work is left for the backend server.

For Casbin.js, model configuration is transparent. What Casbin.js concerns about are the actions and the objects. It doesn't know if the developer are using RBAC or other access-control mechanism. So I believe the core API of Casbin.js should be quite simple as follows.

Some basic API for Casbin.js enforcer are:
```
setUser(user : string): void. 
Set the identity of the current user.

enforce(action: string, object: string) : boolean
Check if the user (previously set) are able to apply the action on the subject.

getActions() : Array<string>
Return all the actions that the user has.

getObjects(): Array<string>
Return all the objects that related to the user.

getActionsObjects(): Map<string, Array<string>>
Return all the actions and the corresponding applicable objects.

getObjectsActions(): Map<string, Array<string>>
Return all the objects and the corresponding actions applicable on that.
```
This enforcer's APIs are the cores of Casbin.js. Only after we have finished this part can we going further to design other features serving for manipulating frontend operations (like controling the permissions for web UI elements).

**Comment by hsluoyz** [comment]
@Ishaan28malik we had made some progress on this project, as you can see in the commits. Are you still willing to contribute it? Like fixing this repo or making a React or Vue wrapper for this library?

**Comment by Ishaan28malik** [comment]
@hsluoyz sure I would love to contribute and work on this.

**Comment by ThomasLohmann** [comment]
@hsluoyz @Ishaan28malik any plans to support Angular? It would be really great!

Best regards,
Thomas

**Comment by hsluoyz** [comment]
@ThomasLohmann can you create a new GitHub issue so we can track its progress ? Thanks!
